apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mypyspark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mypyspark
    spec:
      containers:
      - name: mypysprkpod
        image: databricksprod.azurecr.io/mypyspark:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

